FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ["startdb.sh", "startdb.sh"]
RUN dotnet tool install --global dotnet-ef

COPY . . 
WORKDIR /src/CarsService.API

RUN chmod +x startdb.sh
CMD /bin/bash startdb.sh